import os

WTF_CSRF_ENABLED = True
SECRET_KEY = os.environ["FLASK_SECRET_KEY"]
SESSION_COOKIE_SECURE = True
REMEMBER_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
REMEMBER_COOKIE_HTTPONLY = True
PSQL_SEARCH_USER_PASS = os.environ["PSQL_SEARCH_USER_PASS"]
PSQL_APACHE_USER_PASS = os.environ["PSQL_APACHE_USER_PASS"]
